[project]
name = "portfolio-source"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zeke King", email = "15235033+zekeking@users.noreply.github.com" }
]
requires-python = ">=3.11.8"
dependencies = []

[project.scripts]
portfolio-source = "portfolio_source:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "zensical>=0.0.59",
]
